### ISSUE TITLE
百度地图初始化引起的Crash

### ISSUE THREAD

**Issue by stevenwsg** [easemob/easeui#220]
使用的版本：
    implementation 'io.hyphenate:ease-im-kit:3.8.3'
    implementation 'io.hyphenate:hyphenate-chat:3.8.3'

聊天时点击发送位置，发生crash。堆栈为：
07-11 12:12:33.143 1916-1916/com.wsg.xsybbs E/CrashReport: Java Crash Happen cause by main(1)
07-11 12:12:33.154 1916-1916/com.wsg.xsybbs E/CrashReport: stack frame :13, has cause true
07-11 12:12:33.163 1916-1916/com.wsg.xsybbs E/CrashReport: #++++++++++Record By Bugly++++++++++#
07-11 12:12:33.163 1916-1916/com.wsg.xsybbs E/CrashReport: # You can use Bugly(http:\\bugly.qq.com) to get more Crash Detail!
07-11 12:12:33.163 1916-1916/com.wsg.xsybbs E/CrashReport: # PKG NAME: com.wsg.xsybbs
07-11 12:12:33.163 1916-1916/com.wsg.xsybbs E/CrashReport: # APP VER: 1.0
07-11 12:12:33.163 1916-1916/com.wsg.xsybbs E/CrashReport: # SDK VER: 3.3.92
07-11 12:12:33.163 1916-1916/com.wsg.xsybbs E/CrashReport: # LAUNCH TIME: 2021-07-11 12:07:28
07-11 12:12:33.163 1916-1916/com.wsg.xsybbs E/CrashReport: # CRASH TYPE: JAVA_CRASH
07-11 12:12:33.163 1916-1916/com.wsg.xsybbs E/CrashReport: # CRASH TIME: 2021-07-11 12:12:33
07-11 12:12:33.163 1916-1916/com.wsg.xsybbs E/CrashReport: # CRASH PROCESS: com.wsg.xsybbs
07-11 12:12:33.163 1916-1916/com.wsg.xsybbs E/CrashReport: # CRASH THREAD: main
07-11 12:12:33.163 1916-1916/com.wsg.xsybbs E/CrashReport: # REPORT ID: 9398fd2f-daef-4612-9a08-a112b85fe7dc
07-11 12:12:33.163 1916-1916/com.wsg.xsybbs E/CrashReport: # CRASH DEVICE: MuMu UNROOT
07-11 12:12:33.163 1916-1916/com.wsg.xsybbs E/CrashReport: # RUNTIME AVAIL RAM:6515027968 ROM:133846048768 SD:133846048768
07-11 12:12:33.163 1916-1916/com.wsg.xsybbs E/CrashReport: # RUNTIME TOTAL RAM:3715092480 ROM:135148310528 SD:135148310528
07-11 12:12:33.163 1916-1916/com.wsg.xsybbs E/CrashReport: # CRASH STACK: 
07-11 12:12:33.163 1916-1916/com.wsg.xsybbs E/CrashReport: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/baidu/mapapi/SDKInitializer;
        at com.hyphenate.easeui.ui.EaseBaiduMapActivity.onCreate(EaseBaiduMapActivity.java:90)
        at android.app.Activity.performCreate(Activity.java:6279)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2463)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2570)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1420)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5606)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.baidu.mapapi.SDKInitializer" on path: DexPathList[[zip file "/data/app/com.wsg.xsybbs-1/base.apk"],nativeLibraryDirectories=[/data/app/com.wsg.xsybbs-1/lib/x86, /data/app/com.wsg.xsybbs-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.hyphenate.easeui.ui.EaseBaiduMapActivity.onCreate(EaseBaiduMapActivity.java:90) 
        at android.app.Activity.performCreate(Activity.java:6279) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2463) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2570) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1420) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5606) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635) 
    	Suppressed: java.lang.ClassNotFoundException: com.baidu.mapapi.SDKInitializer
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 14 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
07-11 12:12:33.163 1916-1916/com.wsg.xsybbs E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#
07-11 12:12:33.269 1916-1916/? E/CrashReport: sys default last handle start!
    
    --------- beginning of crash
07-11 12:12:33.269 1916-1916/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.wsg.xsybbs, PID: 1916
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/baidu/mapapi/SDKInitializer;
        at com.hyphenate.easeui.ui.EaseBaiduMapActivity.onCreate(EaseBaiduMapActivity.java:90)
        at android.app.Activity.performCreate(Activity.java:6279)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2463)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2570)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1420)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5606)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.baidu.mapapi.SDKInitializer" on path: DexPathList[[zip file "/data/app/com.wsg.xsybbs-1/base.apk"],nativeLibraryDirectories=[/data/app/com.wsg.xsybbs-1/lib/x86, /data/app/com.wsg.xsybbs-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.hyphenate.easeui.ui.EaseBaiduMapActivity.onCreate(EaseBaiduMapActivity.java:90) 
        at android.app.Activity.performCreate(Activity.java:6279) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2463) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2570) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1420) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5606) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635) 
    	Suppressed: java.lang.ClassNotFoundException: com.baidu.mapapi.SDKInitializer
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 14 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
07-11 12:12:33.283 653-685/? E/InputDispatcher: channel 'bf7505b com.wsg.xsybbs/com.wsg.xsybbs.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
07-11 12:12:33.284 653-685/? E/InputDispatcher: channel '11b84b1 com.wsg.xsybbs/com.wsg.xsybbs.activity.ChatActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
07-11 12:12:33.560 2036-2036/com.wsg.xsybbs E/CrashReport: --------------------------------------------------------------------------------------------
07-11 12:12:33.560 2036-2036/com.wsg.xsybbs E/CrashReport: --------------------------------------------------------------------------------------------
07-11 12:12:33.925 2036-2036/com.wsg.xsybbs E/EMPushConfig: senderId can't be empty when enable FCM push !
07-11 12:12:33.927 2036-2036/com.wsg.xsybbs E/EMPushHelper: EMPushHelper init, config: EMPushConfig{fcmSenderId='null', hwAppId='null', miAppId='null', miAppKey='null', mzAppId='null', mzAppKey='null', oppoAppKey='null', oppoAppSecret='null', vivoAppId='null', vivoAppKey='null', enabledPushTypes=[]}
07-11 12:12:33.946 2036-2036/com.wsg.xsybbs E/EMClient: is autoLogin : true
07-11 12:12:33.946 2036-2036/com.wsg.xsybbs E/EMClient: lastLoginUser : wsg
07-11 12:12:33.946 2036-2036/com.wsg.xsybbs E/EMClient: hyphenate SDK is initialized with version : 3.8.3

是我初始化的方式有问题嘛？内部找不到百度初始化这个类

**Comment by jinanzhuan** [comment]
如果你使用的是imkit中提供的默认的地图拓展项，那么就需要你在主module引入百度地图相关的jar和so文件

**Comment by stevenwsg** [comment]
> 如果你使用的是imkit中提供的默认的地图拓展项，那么就需要你在主module引入百度地图相关的jar和so文件

你们的sdk已经集成了这些了，还需要我在集成嘛
我看打出来的包，包含百度地图相关的jar和so文件

**Comment by jinanzhuan** [comment]
> > 如果你使用的是imkit中提供的默认的地图拓展项，那么就需要你在主module引入百度地图相关的jar和so文件
> 
> 你们的sdk已经集成了这些了，还需要我在集成嘛
> 我看打出来的包，包含百度地图相关的jar和so文件

IM SDK没有继承百度地图，在imkit这个UI库中，只是用"compileOnly files('libs/BaiduLBS_Android.jar')"，只编译。如果不想用百度地图的话，可以不用在主module中导入，同时通过imkit提供的api去掉地图定位这一项，在AndroidManifest.xml中不要注册EaseBaiduMapActivity；如果想要使用百度地图的话，就需要在主module中引入相关的jar和so。
如果想使用其他地图，除了上面的去除步骤，还需要你根据imkit中提供的api，添加一项新的拓展项，用于地图点击。当然定位这些逻辑需要你自己实现了。
去除及添加项可以参考demo中的ChatFragment中的resetChatExtendMenu()方法中实现。

**Comment by stevenwsg** [comment]
> 如果你使用的是imkit中提供的默认的地图拓展项，那么就需要你在主module引入百度地图相关的jar和so文件

嗯嗯 这样做问题是解决了。 你们用的是compileOnly， 但是你们集成的百度地图的aar和so还是打进了安装包里面。 和我自己集成的版本重复了。


![image](https://user-images.githubusercontent.com/22788925/126893018-4ede10d5-f052-4de8-b9ec-8c716ffb4ef6.png)


我用这个gradle也去不掉你们的依赖：

    implementation 'io.hyphenate:ease-im-kit:3.8.3', {
        exclude group:'io.hyphenate', module: 'BaiduLBS_Android'
    }
    implementation 'io.hyphenate:hyphenate-chat:3.8.3'

有好的办法解决嘛

**Comment by stevenwsg** [comment]
> 如果你使用的是imkit中提供的默认的地图拓展项，那么就需要你在主module引入百度地图相关的jar和so文件


你们内部用的百度地图是4.0 ， 16年的sdk.我集成最新的sdk是7.3.0.已经找不到你们里面的类了。 而且百度官方现在也不提供4.3.0的下载地址了。

不过可以集成你们工程里面的4.0， 但是so已经对不上了。 你们能升级百度地图的SDK版本嘛 4.0的太老了， 16年的事情了 = =

**Comment by jinanzhuan** [comment]
> > 如果你使用的是imkit中提供的默认的地图拓展项，那么就需要你在主module引入百度地图相关的jar和so文件
> 
> 你们内部用的百度地图是4.0 ， 16年的sdk.我集成最新的sdk是7.3.0.已经找不到你们里面的类了。 而且百度官方现在也不提供4.3.0的下载地址了。
> 
> 不过可以集成你们工程里面的4.0， 但是so已经对不上了。 你们能升级百度地图的SDK版本嘛 4.0的太老了， 16年的事情了 = =

好的，我们这块再看一下。可以加一下环信的官方技术群：980107327，方便及时看到你的反馈。

**Comment by jinanzhuan** [comment]
> > 如果你使用的是imkit中提供的默认的地图拓展项，那么就需要你在主module引入百度地图相关的jar和so文件
> 
> 嗯嗯 这样做问题是解决了。 你们用的是compileOnly， 但是你们集成的百度地图的aar和so还是打进了安装包里面。 和我自己集成的版本重复了。
> 
> ![image](https://user-images.githubusercontent.com/22788925/126893018-4ede10d5-f052-4de8-b9ec-8c716ffb4ef6.png)
> 
> 我用这个gradle也去不掉你们的依赖：
> 
> ```
> implementation 'io.hyphenate:ease-im-kit:3.8.3', {
>     exclude group:'io.hyphenate', module: 'BaiduLBS_Android'
> }
> implementation 'io.hyphenate:hyphenate-chat:3.8.3'
> ```
> 
> 有好的办法解决嘛

目前的话，你可以尝试用如下方法将指定的.so文件排除，看是否可以解决，build.gradle(Module: app)里面：
 ```
    packagingOptions {
        exclude 'lib/armeabi/xxx.so'
    }
```
参考：https://blog.csdn.net/gengkui9897/article/details/88928584

**Comment by stevenwsg** [comment]
> > > 如果你使用的是imkit中提供的默认的地图拓展项，那么就需要你在主module引入百度地图相关的jar和so文件
> > 
> > 
> > 你们内部用的百度地图是4.0 ， 16年的sdk.我集成最新的sdk是7.3.0.已经找不到你们里面的类了。 而且百度官方现在也不提供4.3.0的下载地址了。
> > 不过可以集成你们工程里面的4.0， 但是so已经对不上了。 你们能升级百度地图的SDK版本嘛 4.0的太老了， 16年的事情了 = =
> 
> 好的，我们这块再看一下。可以加一下环信的官方技术群：980107327，方便及时看到你的反馈。

嗯嗯 好的 谢谢~

**Comment by jinanzhuan** [comment]
在imkit 3.8.5版本中已经将百度地图的so文件移除，需要升级百度地图版本的话，不会受到imkit中so文件的干扰。
